pasta_tcc/tcc/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    # index
    # incluindo na index as urls do app usuarios
    path('',include('usuarios.urls')),
    path('anotacoes/',include('anotacoes.urls')),
    path('grupo/', include('grupos.urls')),
    path('tarefa/',include('tarefas.urls')),
    path('admin/', admin.site.urls),

]

pasta_tcc/tarefas/models.py
from django.db import models

# importando da model  User do django

from django.contrib.auth.models import User

from grupos.models import Grupo

from datetime import datetime

# Create your models here.

class Tarefas(models.Model):
    title = models.CharField(max_length=200,blank=False) # campo obrigatorio 
    body = models.TextField(blank=True) # campo pode ser vazio 
    date_start = models.DateField(blank = False, null =False)
    date_completion = models.DateField(blank = True, null = True ) # data que a tarefa foi concluida, por isso deve ser vazio no inicio do criar tarefa 
    status = models.CharField(blank= True, null = True, max_length = 200 )
    date= models.DateField(default=datetime.now,blank=True)
    fk_pessoa = models.ForeignKey(User, on_delete = models.CASCADE, blank= True) # pode ser o username da pessoa ou id, tanto faz 
    fk_grupo = models.ForeignKey(Grupo, on_delete = models.CASCADE, null= True, blank=True ) # o grupo pode ser vazio(null) no banco de dados e blank true para vazio
    


   
   

  

  

pasta_tcc/templates/cadastrar.html
{% extends 'partials/base.html' %}

{% block title %} Criar conta  {% endblock %}
{% block content %}
{% load widget_tweaks %}
    {% include 'partials/menu.html' %}


<section class="col-8"> 
    <form action="{% url 'insertUsuario' %}" method="POST">
        {% csrf_token %}
        {% for field in formulario_cadastro.visible_fields %}
        <div class="form-group">
            <label for="{{field.id_for_label}}"> {{field.label}} </label>
            {{field|add_class:'form-control'}}
        </div>
        {%  for error in field.errors %}
        <section class="alert alert-danger mt-2" role="alert">
            {{ field.errors }}
         </section>
</section>
        {% endfor %}
        {% endfor %}
        <input type="submit" value="criar conta" class="btn btn-success mt-2">
    </form>

    já tem uma conta ? clique  <a href="{% url 'index' %}"> aqui para logar </a>
</section>

{% endblock %}

pasta_tcc/templates/dashboard.html
{%  extends 'partials/base.html' %}
{% block title %} Dashboard  {% endblock %}

{% block content %}
    {% include 'partials/menu.html' %}
    <h1> bem vindo nick: {{user.username}}</h1>
    <h3> Anotações </h3>
    {% if anotacoes %}
    <table class="table">
        <thead>
            <tr>
              <th scope="col">id Anotação </th>
              <th scope="col">Titulo</th>
              <th scope="col">Mensagem</th>
              <th scope="col">Id usuario</th>
              <th scope="col">Grupo</th>
              <th scope="col">Data </th>
              <th scope="col">Editar</th>
              <th scope="col">Apagar</th>
            </tr>
          </thead>
          <tbody>

         
    {% for anotacoes_usuarios in anotacoes %}
        <tr>
          <td> {{ anotacoes_usuarios.id }} </td>
          <td> {{anotacoes_usuarios.title }} </td>
          <td> {{anotacoes_usuarios.body }} </td>
          <td> {{anotacoes_usuarios.fk_pessoa_id }} </td>
          <td> 
            {% if anotacoes_usuarios.fk_grupo == None%}
             -
            {% else %}
              {{anotacoes_usuarios.fk_grupo.title}}
            {% endif %}  
          </td>
          <td>
            {{anotacoes_usuarios.date}}
          </td>
          <td> <a href="{% url 'editar_anotacao' anotacoes_usuarios.id  %}" title="{{anotacoes_usuarios.id}}"> Editar  </a> </td>
          <td> <a href="{% url 'deleta_anotação' anotacoes_usuarios.id %}" title="{{anotacoes_usuarios.id}}"> Apagar  </a> </td>
           <!-- {% url 'deleta_anotação' anotacoes_usuarios.id %} -->
          
        </tr>
    {% endfor %}
        </tbody>
    </table>
    {% else %}
  
    {% endif %}
   

      
{% endblock %}

pasta_tcc/templates/editar_anotacoes.html
{% extends 'partials/base.html' %}
{% block title %} Editar Anotação  {% endblock %}




{% block content%}
{% load widget_tweaks %}

    {% include 'partials/menu.html' %}
    
    <section class="col-8"> 
    <form action="{% url 'atualizar_anotacao' %}" method="POST">
        {% csrf_token %}
        {% for field in form_anotacoes_atualizar %}
        <div class="form-group">
            <label for="{{field.id_for_label}}"> {{field.label}} </label>
            {{field|add_class:'form-control'}}
        </div>
             {%  for error in field.errors %}
                <section class="alert alert-danger mt-2" role="alert">
                    {{ field.errors }}
             </section>
             {% endfor %}
        {% endfor %}
        <div class="form-group">
            <label for="fk_grupo_edit_label"> Grupo:</label>
            <select name="fk_grupo_edit" id="" class="form-control">
                {% if grupo_edit %}
               
                    <option value="{{grupo_edit.id}}" selected> {{grupo_edit.title}} </option>
                    <option value="" > sem grupo </option>
                    {% for grupos_disponiveis in valores_grupos_editar %}
                    <option value="{{grupos_disponiveis.id}}" > {{grupos_disponiveis.title}} </option>
                    {% endfor %}
                  
                {% else %}
                <option value=""> Nenhum grupo selecionado  </option>
                {% for grupos_disponiveis in valores_grupos_editar %}
                <option value="{{grupos_disponiveis.id}}" > {{grupos_disponiveis.title}} </option>
                {% endfor %}
                {% endif %}
            </select>
           
           
           

        </div>       
     
        {% include 'partials/alertas.html' %}

        <input type="hidden" value="{{id_anotacao}}" name='id_anotacao' readonly>
        <input type="submit" value="editando Anotação" class="btn btn-success mt-2">
    </form>
   
   
</section>

{% endblock %}

pasta_tcc/templates/editar_tarefa.html
{% extends 'partials/base.html' %}
{% block title %} Editar Anotação  {% endblock %}




{% block content%}
{% load widget_tweaks %}

    {% include 'partials/menu.html' %}
    
    <section class="col-8"> 
    <form action="{% url 'atualizar_tarefa' %}" method="POST">
        {% csrf_token %}
        {% for field in form_tarefa_atualizar %}
        <div class="form-group">
            <label for="{{field.id_for_label}}"> {{field.label}} </label>
            {{field|add_class:'form-control'}}
        </div>
             {%  for error in field.errors %}
                <section class="alert alert-danger mt-2" role="alert">
                    {{ field.errors }}
             </section>
             {% endfor %}
        {% endfor %}
        <div class="form-group">
            <label for="fk_grupo_edit_label"> Grupo:</label>
            <select name="fk_grupo_edit" id="" class="form-control">
                {% if grupo_edit %}
               
                    <option value="{{grupo_edit.id}}" selected> {{grupo_edit.title}} </option>
                    <option value="" > sem grupo </option>
                    {% for grupos_disponiveis in valores_grupos_editar %}
                    <option value="{{grupos_disponiveis.id}}" > {{grupos_disponiveis.title}} </option>
                    {% endfor %}
                  
                {% else %}
                <option value=""> Nenhum grupo selecionado  </option>
                {% for grupos_disponiveis in valores_grupos_editar %}
                <option value="{{grupos_disponiveis.id}}" > {{grupos_disponiveis.title}} </option>
                {% endfor %}
                {% endif %}
            </select>
           
           
           

        </div>       
     
        {% include 'partials/alertas.html' %}

        <input type="hidden" value="{{id_tarefa}}" name='id_tarefa' readonly>
        <input type="submit" value="editando Anotação" class="btn btn-success mt-2">
    </form>
   
   
</section>

{% endblock %}

pasta_tcc/templates/excluir_grupo.html
{% extends 'partials/base.html' %}
{% block title %} Excluir grupo  {% endblock %}

{% block content%}
    {% include 'partials/menu.html' %}
    {% if grupo_deletar %}
        <h3> Informações do grupo {grupo_deletar.id} </h3>
        <section class="col-8"> 
            {% for valores in  grupo_deletar%}
                <div class='form-group mt-3'>
                    <label for="" class=" mt-3 mb-3" > Titulo </label>
                    <input type="text" class="form-control" readonly value="{{valores.title}}">
                   
                </div>
                <div class='form-group mt-3'>
                    <label for="" class=" mt-3 mb-3"> Descrição  </label>
                    <textarea cols="40"  rows="10"  class="form-control" readonly value="#"> {{valores.description}} </textarea>
                   
                </div>
                <div class='form-group mt-3'>
                    <label for="" class=" mt-3 mb-3"> Cor  </label>
                    <input type="color" class="form-control"  value="{{valores.color}}" disabled>
                   
                </div>
              
                <h4 class="mt-3"> Observações</h4>
                <p>
                    Ao apagar o seu grupo todas as suas anotações ou tarefas poderão ser deletadas.Caso queira você pode apenas apagar seu grupo e manter suas anotações ou tarefas 
                </p>
                <a href="{%  url 'apagar_grupo' valores.id  'deletar_tudo' %}" class="btn btn-danger"> Deletar tudo </a>
                <a href="{%  url 'apagar_grupo' valores.id 'deletar_apenas_grupo' %}" class="btn btn-danger"> Apagar apenas grupo  </a>
                <a href="{% url 'listar_grupos' %}" class="btn btn-success"> Voltar pagina inicial  </a>
            {% endfor %}
            
            
            
            
            
            
            
    </section>
       
       
       
       
       
       
       
       
       
    {% else %}
        Erro, volte para a Dashboard
    {% endif %}
{% endblock %}

pasta_tcc/templates/form_anotacoes.html
{% extends 'partials/base.html' %}
{% block title %} Criar Anotação  {% endblock %}




{% block content%}
{% load widget_tweaks %}
    {% include 'partials/menu.html' %}
   
    <section class="col-8"> 
    <form action="{% url 'insert_anotacoes' %}" method="POST">
        {% csrf_token %}
        {% for field in form_anotacoes.visible_fields %}
        <div class="form-group">
            <label for="{{field.id_for_label}}"> {{field.label}} </label>
            {{field|add_class:'form-control'}}
        </div>
             {%  for error in field.errors %}
                <section class="alert alert-danger mt-2" role="alert">
                    {{ field.errors }}
             </section>
             {% endfor %}
        {% endfor %}
       
       <div class="form-group">
            <label for="label_fk_grupo"> Grupo(opcional) </label>
            <select name="fk_grupo" id="id_fk_grupo" class="form-control">
                <option value="" selected> Selecione um grupo </option>
                {% if grupo %}
                {% for valores in grupo %}
                    <option value="{{valores.id}}"> {{valores.title}} </option>
                
                {% endfor %}
                
              
              
              

              
                {% endif %}
               
               
                              
            </select>
        </div>  
       
       
       
       
       
       
       

        {% include 'partials/alertas.html' %}
        <input type="submit" value="criar Anotação" class="btn btn-success mt-2">
    </form>
   
</section>

{% endblock %}

pasta_tcc/templates/form_criarGrupo.html
{% extends 'partials/base.html' %}
{% block title %} Criar Grupo  {% endblock %}

{% block content %}
    {% load widget_tweaks %}
    {% include 'partials/menu.html' %}
    <h2 class="mb-3"> Grupo para anotações ou tarefas </h2>
    <section class="col-8">
        <form action="{% url 'insert_grupo' %}" method="POST">
          {% csrf_token %}
          {% for field in form_grupo_insert.visible_fields %}
            <div class='form-group'>
                <label for="{{field.id_for_label}}"> {{field.label}} </label>
               
                {{field|add_class:'form-control'}}
            </div>
                {%  for error in field.errors %}
                    <section class="alert alert-danger mt-2" role="alert">
                    {{ field.errors }}
                    </section>
                {% endfor %}
            {% endfor %}
        
            {% include 'partials/alertas.html' %}
            <input type="submit" value="criar grupo" class="btn btn-success mt-2">

        </form>

    </section>
{% endblock %}

pasta_tcc/templates/form_editar_grupo.html
{% extends  'partials/base.html' %}
{% block title %} Editar grupo   {% endblock %}
{% block content %}
{% load widget_tweaks %}
    {% include 'partials/menu.html' %}

    <h4> Editar grupo </h4>

    <section class="col-8">
        <form action="{% url 'atualizar_grupo' %}" method="POST">
            {% csrf_token %}
            {% for field in form_grupo_edit %}
                <div class="form-group">
                    <label for="{{field.id_for_label}}"> {{field.label}} </label>
                    {{field|add_class:'form-control'}}
                </div>
                {%  for error in field.errors %}
                <section class="alert alert-danger mt-2" role="alert">
                    {{ field.errors }}
             </section>
             {% endfor %}
            {% endfor %}
            <input type="hidden" value="{{id_grupo}}" name="id_grupo_edit">
            <input type="submit" value="editar grupo" class=" btn btn-success mt-2">
        </form>
    </section>
{% endblock %}

pasta_tcc/templates/form_tarefas.html
{% extends 'partials/base.html' %}
{% block title %} Criar Anotação  {% endblock %}




{% block content%}
{% load widget_tweaks %}
    {% include 'partials/menu.html' %}
   <h3> formulario de tarefa </h3>
    <section class="col-8"> 
    <form action="{% url 'insert_tarefa' %}" method="POST">
        {% csrf_token %}
        {% for field in form_tarefa.visible_fields %}
        <div class="form-group">
            <label for="{{field.id_for_label}}"> {{field.label}} </label>
            {{field|add_class:'form-control'}}
        </div>
             {%  for error in field.errors %}
                <section class="alert alert-danger mt-2" role="alert">
                    {{ field.errors }}
             </section>
             {% endfor %}
        {% endfor %}
       
       <div class="form-group">
            <label for="label_fk_grupo"> Grupo(opcional) </label>
            <select name="fk_grupo" id="id_fk_grupo" class="form-control">
                <option value="" selected> Selecione um grupo </option>
                {% if grupo %}
                {% for valores in grupo %}
                    <option value="{{valores.id}}"> {{valores.title}} </option>
                
                {% endfor %}
               
               
                
              
              
              

              
                {% endif %}
               
               
                              
            </select>
        </div>  
       
       
       
       
       
       
       

        {% include 'partials/alertas.html' %}
        <input type="submit" value="criar tarefa" class="btn btn-success mt-2">
    </form>
   
</section>

{% endblock %}

pasta_tcc/templates/index.html
{% extends 'partials/base.html' %}
{% block title %} Login  {% endblock %}




{% block content%}
{% load widget_tweaks %}
    {% include 'partials/menu.html' %}
    <section class="col-8"> 
    <form action="{% url 'logar'%}" method="POST">
        {% csrf_token %}
        {% for field in login_form.visible_fields %}
        <div class="form-group">
            <label for="{{field.id_for_label}}"> {{field.label}} </label>
            {{field|add_class:'form-control'}}
        </div>
             {%  for error in field.errors %}
                <section class="alert alert-danger mt-2" role="alert">
                    {{ field.errors }}
             </section>
             {% endfor %}
        {% endfor %}

        {% include 'partials/alertas.html' %}
        <input type="submit" value="criar conta" class="btn btn-success mt-2">
    </form>
    Não tem conta ? clique  <a href="{% url 'cadastrar' %}"> aqui para criar uma  </a>
</section>

{% endblock %}

pasta_tcc/templates/listar_grupos.html
{% extends 'partials/base.html' %}
{% block title %} Grupos  {% endblock %}

{% block content%}
    {% include 'partials/menu.html' %}
        <h1> Seus grupos </h1>
        {% if grupos %}
            <table class="table">
                <thead>
                    <tr>
                      <th scope="col">id grupo </th>
                      <th scope="col">Titulo</th>
                      <th scope="col">descrição </th>
                      <th scope="col">fk_pessoa_id</th>
                      <th scope="col">apagar </th>
                      <th scope="col">Editar </th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for valores_grupos in grupos %}
                        <tr>
                            <td> {{valores_grupos.id}} </td>
                            <td> {{valores_grupos.title}} </td>
                            <td> {{valores_grupos.description}} </td>
                            <td> {{valores_grupos.fk_pessoa_id}} </td>
                            <td> <a href="{% url 'pagina_deletar_grupo' valores_grupos.id %}" title="{{valores_grupos.id}}"> Apagar  </a> </td>
                            <td> <a href="{% url 'pagina_editar_grupo' valores_grupos.id %}" title="{{valores_grupos.id}}"> Editar  </a> </td>
                        </tr>
                    {% endfor %}
                  </tbody>
            </table>
        {% endif %}
{% endblock %}

pasta_tcc/templates/listar_tarefas.html
{% extends 'partials/base.html' %}
{% block title %} Grupos  {% endblock %}

{% block content%}
    {% include 'partials/menu.html' %}
        <h1> Suas tarefas </h1>
        {% if tarefas %}
            <table class="table">
                <thead>
                    <tr>
                      <th scope="col">id tarefa </th>
                      <th scope="col">titulo da tarefa  </th>
                      <th scope="col"> corpo </th>
                      <th scope="col">data de inicio  </th>
                      <th scope="col">data máxima para concluir  </th>
                      <th scope="col">criado em   </th>
                      <th scope="col">status  </th>
                      <th scope="col">grupo  </th>
                      <th scope="col">Apagar   </th>
                      <th scope="col">editar  </th>
                      <th scope="col">Concluir tarefa  </th>
                   
                   

                    
                    
                     
                     
                      
                    </tr>
                  </thead>
                  <tbody>
                    {% for valores_grupos in tarefas %}
                        <tr>
                            <td> {{valores_grupos.id}} </td>
                            <td> {{valores_grupos.title}} </td>
                            <td> {{valores_grupos.body}} </td>
                            <td> {{valores_grupos.date_start}} </td>
                            <td> {{valores_grupos.date_completion}} </td>
                            <td> {{valores_grupos.date}} </td>
                            <td> {{valores_grupos.status}} </td>
                            <td>
                                {% if valores_grupos.fk_grupo == None%}
                                -
                               {% else %}
                                 {{valores_grupos.fk_grupo.title}}
                               {% endif %}  


                            </td>
                            <td> <a href="{% url 'deletar_tarefa' valores_grupos.id %}" title="{{valores_grupos.id}}"> Apagar  </a> </td>
                            <td> <a href="{% url 'editar_tarefa' valores_grupos.id %}" title="{{valores_grupos.id}}"> Editar  </a> </td>
                            <td> <a href="#" title="{{valores_grupos.id}}"> Concluir tarefa  </a> </td>
                        </tr>
                    {% endfor %}
                  </tbody>
            </table>
        {% endif %}
{% endblock %}